stages:
  - build

build:
  image:
    name: ubuntu:bionic
  stage: build
  script:
    - apt-get -yqq update && apt-get -yqq install gettext
    - ./get-k0s.sh
    - dpkg-deb -b kubanetes
  artifacts:
    paths:
      - kubanetes.deb

